import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/sidebar/sidebar";
import { TaskProvider } from "../contexts/taskcontext";

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TaskProvider>
      <SidebarProvider>
        <AppSidebar/>
        <main>
          <SidebarTrigger/>
          {children}
        </main>
      </SidebarProvider>
    </TaskProvider>
  );
}
