import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/sidebar/sidebar";
import { TaskProvider } from "../contexts/taskcontext";
import { UserProvider } from "../contexts/usercontext";

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <TaskProvider>
        <SidebarProvider>
          <AppSidebar/>
          <main className="w-full">
            <SidebarTrigger/>
            {children}
          </main>
        </SidebarProvider>
      </TaskProvider>
    </UserProvider>
  );
}
